


    <div class="mainMovies">
        <article>
            <h2> <?= $myMovie['title_m'] ?> </h2>
            <img class="poster" src="<?= $myMovie['poster_m']; ?>" alt="<?= $myMovie['title_m']; ?>">
            <p><?= $myMovie['full_plot_m']; ?></p>
            <p class="coma">De : 
                <?php foreach($directors as $director) :?>
                    <a href="<?= $requestUrl ?>/directors/director?id_d=<?= $director['id_d'] ?>">
                        <?= $director['firstname_d']; ?> <?= $director['lastname_d']; ?>, 
                    </a>
                
                <?php endforeach; ?>
            </p>
            <p class="coma">Avec : 
                <?php foreach($actors as $actor) :?>
                    <a href="<?= $requestUrl ?>/actors/actor?id_a=<?= $actor['id_a'] ?>">
                        <?= $actor['firstname_a']; ?> <?= $actor['lastname_a']; ?>, 
                    </a>
                    

                <?php endforeach; ?>
            </p>
            <p class="coma">Genre(s) : 
                <?php foreach($genres as $genre) :?>
                    <a href="<?= $requestUrl ?>/genres/genre?id_g=<?= $genre['id_g'] ?>">
                        <?= $genre["name_g"]; ?>, 
                    </a>
                    
                <?php endforeach; ?>
            </p>
        </article>
    </div>