<section class="formu">
	<h2><i class="fa fa-user"></i> Création d'un compte client</h2>

	<form class="generic-form" action="<?= $requestUrl ?>/user" method="POST">

		<aside class="error-message hidden">
			<h3><i class="fa fa-warning"></i> Il y a <span id="total-error-count">1</span> erreur(s) dans le formulaire !</h3>
			<p><?= $errorMessage ?></p>
		</aside> 

		<fieldset>
			<legend><i class="fa fa-book"></i> Identité et coordonnées</legend>
			<ul>
				<li>
					<label for="login">login :</label>
					<input id="login" type="text" name="login" data-required data-name="login">
				</li>
				<li>
					<label for="birthDay">Date de naissance :</label>
					<select id="birthDay" name="birthDay">
						<?php for($day = 1; $day <= 31; $day++): ?>
							<option value="<?= $day ?>"><?= $day ?></option>
						<?php endfor; ?>
					</select>
					<span> / </span>
					<select name="birthMonth">
						<option value="1">Janvier</option>
						<option value="2">Février</option>
						<option value="3">Mars</option>
						<option value="4">Avril</option>
						<option value="5">Mai</option>
						<option value="6">Juin</option>
						<option value="7">Juillet</option>
						<option value="8">Août</option>
						<option value="9">Septembre</option>
						<option value="10">Octobre</option>
						<option value="11">Novembre</option>
						<option value="12">Décembre</option>
					</select>
					<span> / </span>
					<select name="birthYear">
						<?php for($year = 1940; $year <= date('Y') - 18; $year++): ?>
							<option value="<?= $year; ?>"><?= $year; ?></option>
						<?php endfor; ?>
					</select>
				</li>
		</fieldset>

		<fieldset>
			<legend><i class="fa fa-lock"></i> Informations d'authentification</legend>
			<ul>
				<li>
					<label for="email">E-mail :</label>
					<input id="email" type="text" name="email" data-required data-name="E-mail" value="<?= $email ?>">
				</li>
				<li>
					<label for="password">Mot de passe :</label>
					<input id="password" type="password" name="password" data-required data-name="Mot de passe" data-length="8">
				</li>
			</ul>
		</fieldset>

		<ul>
			<li>
				<input class="button button-primary" type="submit" value="Créer le compte">
				<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
			</li>
		</ul>
	</form>
</section>