	<h2><i class="fa fa-user"></i> Création d'un administrateur</h2>

<form class="generic-form" action="<?= $requestUrl ?>/admin/user" method="POST">

	<aside class="error-message hidden">
		<h3><i class="fa fa-warning"></i> Il y a <span id="js-total-error-count">1</span> erreur(s) dans le formulaire !</h3>
		<p><?= $errorMessage ?></p>
	</aside>

	<fieldset>
		<legend><i class="fa fa-lock"></i> Informations d'authentification</legend>
		<ul>
	        <li>
	            <label for="email">E-mail :</label>
	            <input id="email" type="text" name="email" data-required data-name="E-mail" value="<?= $email ?>">
	        </li>
	        <li>
	            <label for="password">Mot de passe :</label>
	            <input id="password" type="password" name="password" data-required data-name="Mot de passe" data-length="8">
	        </li>
		</ul>
	</fieldset>

	<ul>
		<li>
			<input class="button button-primary" type="submit" value="Créer le compte">
			<a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
		</li>
	</ul>
</form> 
<form class="generic-form" action="<?= $requestUrl ?>/admin/user" method="POST">
	<table class="generic-table meal-list">
		<thead>
			<tr>
				<th>Prénom</th>
				<th>Nom</th>
				<th>mail</th>
				<th>Select</th>
			</tr>
		</thead>
		<tbody>
				<?php foreach ($users as $user): ?>
			<tr>
				<td><?= $user['FirstName'] ?></td>
				<td><?= $user['LastName'] ?></td>
				<td><?= $user['Email'] ?></td>
				<td><input type="checkbox" name="<?= $user['Admin'] ?>"
					<?php if($user['Admin']==33): ?>
					checked
					<?php endif; ?>
					></td>
			</tr>
				<?php endforeach ?>
		</tbody>
	</table>
</form>