
<!-- Message de notification -->
<?php if($flashBag->hasMessages() == true): ?>
    <aside id="notice" class="notice">
        <?php foreach($flashBag->fetchMessages() as $message): ?>
            <p><?= $message ?></p>
        <?php endforeach ?>
    </aside>
<?php endif; ?>




<!-- Liste des movies -->
    <div class="mainMovies" id= "mydiv">
    <?php foreach($moviesMain as $movie): ?>
        <article class="roller-item" id="<?= $movie['id_m'] ?>">
            <a class="poster" href="<?= $requestUrl ?>/movie?id_m=<?= $movie['id_m'] ?>">
                <img class="main" src="<?= $movie['poster_m']; ?>" alt="<?= $movie['title_m']; ?>">
                <strong><?= $movie['title_m']; ?></strong>
            </a>
        </article>
        <?php endforeach; ?>
        <!-- <ul id="pages">
            <li class="page">précente</li>
            <?php foreach($Npages as $Npage): ?>
                <li class="page"><?= $Npage ?></li>
            <?php endforeach; ?>
            <li class="page">suivante</li>
        </ul> -->
    </div>
    
